### ISSUE TITLE
Offline

### ISSUE THREAD

**Issue by pergolafabio** [kadrim/proxy4plex#1]
Hey @kadrim , I was following this project for a while , but didn't need it yet... I'm still using orca 2.012 version, I was always in online mode... But since a month or 2 , both my Samsungs are now showing my user offline... Can't login anymore .. I can only access my PMS in offline mode...

Are you aware of a change verry recently on Plex site?

Thnx

See also here I posted:

https://forums.plex.tv/t/plex-app-orca-2-012-showing-user-offline/762872

**Comment by kadrim** [comment]
Not that i did notice.
What Series are you on? E/F/H?

**Comment by pergolafabio** [comment]
They are both H series...

Worked fine untill last week or maybe more.

Now the user icon is always green, verry sometimes it's logged in tough, then it shows blue...
But if I remember correctly it was another color like 2 months ago

**Comment by pergolafabio** [comment]
My PMS is on local, lan, so still can watch ...
But when in offline mode, seems it doesn't advertise anymore as cast player... I used that for Home Assistant and google assistant to play movies by voice

**Comment by pergolafabio** [comment]
It's also strange that I never needed your proxy? Maybe H used already 1.2 ? And only older models were affected?

**Comment by kadrim** [comment]
The h series definitely has higher TLS than E/F

I have both series available so I can test this.

Best bet is to delete plex and reinstall and then use the proxy method

**Comment by pergolafabio** [comment]
Yeah I can do that, need to setup some extra services then... Keep me posted about your H model

Thnx!

**Comment by pergolafabio** [comment]
Is there maybe a log file where I can see something? It probably makes no sense to enable debug mode on PMS, since it can't connect, right? Or would I see something?

**Comment by kadrim** [comment]
Puh. That was a long time ago when that feature worked. But yeah it was showing up in the PMS logs.

But then again not much to gain there. I forced my h series into proxy mode by disconnecting the lan. No problems since then.

But I had similar outages in the last 4 weeks too, before going into proxy mode

**Comment by pergolafabio** [comment]
So maybe there is change then on Plex side

**Comment by pergolafabio** [comment]
Moderator is responding on forum , seems a change on the certificates...

**Comment by ukdtom** [comment]
Just did a reset of an old H serie, and used your Proxy

I see this in the proxy console: `2021/12/09 00:29:40 http: proxy error: tls: first record does not look like a TLS handshake`

Asked Plex if / what they might have changed

**Comment by ukdtom** [comment]
So I agree....No login possible :(

**Comment by ukdtom** [comment]
And I'm the forum mod @pergolafabio  ;)

**Comment by pergolafabio** [comment]
> And I'm the forum mod @pergolafabio ;)

Thnx for feedback, keep us posted :-)

**Comment by kadrim** [comment]
yes, this looks like a change on plex - is the problem still there?

i can verify this tonight (~ 08:00pm UTC). But if the proxy detects a wrong handshake then this really sounds like a wrong certifcate or chain.

**Comment by pergolafabio** [comment]
Indeed , still there , I already noticed a few weeks, mostly I was offline, when I was online, the user icon in left low corner was blue..., But was logged in tough...

I believe the color was different before... Now it's always green (offline) , so adding PMS is not working anymore also.... Lots of users now reporting.... 
Probably related to:
https://forums.plex.tv/t/important-information-about-plex-for-smart-tvs-after-september-30-2021/746506

**Comment by pergolafabio** [comment]
@kadrim , for info, why do we need orca version 2.014 ? is it because there is a new proxy option there where we can setup the proxy ip? is that all thats changed?

**Comment by pergolafabio** [comment]
can i also just use the 2.012 vesion, and just configure my router to intercept all traffic from my samsung tv , and and make a rule to route to the proxy server? am i right the samsung tv is connecting to plex.tv on port 3000 ? If i forward that traffic to your proxy on port 80 ?

	port              = "3000"
	server            = "http://plex.tv"

**Comment by kadrim** [comment]
nope, that won't work because orca implented this feature in a different way, so my proxy has to react a little bit different.

yes you need the 2.014 version - with my proxy the installation is really easy, because of the sideloading capability.

**Comment by pergolafabio** [comment]
yeah, but i can also use 2.012 and setup my router to forward the packets to your proxy, right?

**Comment by kadrim** [comment]
not with that proxy, no.

The proxy will only encapsulate the traffic if the requested url is urlencoded in the GET-Parameter `url`

You can however use another transparent-proxy which will capsulate all traffic. I.e this one: https://github.com/JonCooperWorks/judas

But not everything will work as expected because there are some minor tweaks within Version 2.014 (i.e. the handling of profile-pictures at the login screen).

**Comment by kadrim** [comment]
nope, that most likely won't work, as the plex-app will request the URLs via HTTPS and does check the certificates. so i think you are best off with the 2.014 version

**Comment by pergolafabio** [comment]
ok, thnx for feedback

for now, i'm gonna stick with offlline PMS, still works, thnx for all feedback!!

**Comment by pergolafabio** [comment]
oh, prolly more users are coming to this project now :-) , we are all linking them to here :-)

**Comment by kadrim** [comment]
just verified, using the proxy method on my H-Series (HU7590), the login works as expected. Also linking works.

**Comment by pergolafabio** [comment]
ok cool
