### ISSUE TITLE
Docker container for linux/ARM64 OS

### ISSUE THREAD

**Issue by rah66** [kadrim/proxy4plex#15]
You have a docker container for [Linux/AMD64](https://hub.docker.com/r/kadrim/proxy4plex/tags) OS only, you can make an image for Linux/**ARM64**, this is now the most popular platform.

**Comment by kadrim** [comment]
fixed with [400bd05](https://github.com/kadrim/proxy4plex/commit/400bd056aad382a6f11cd44b4f8902155155f4cd) and [release 0.5.2](https://github.com/kadrim/proxy4plex/releases/tag/0.5.2)
