### ISSUE TITLE
Sideloading process not working with my J series

### ISSUE THREAD

**Issue by mmz06** [kadrim/proxy4plex#2]
Hi,

It seems I need to use your tis proxy solution to make my good old Samsung Orca Plex client to be authenticated through Plex servers since a few days, as I'm appearing offline since a few days.

Model number is UE50JU6800KXZF (2015 gen purchased in 2016)
It’s one of the first Tizen models,but apparently too old to access the official plex client…
I’ve been happy with Orca’s until today, even using 4K HDR content.
Anyway, i tried to login as user “develop”, password “000000”, which works.
Then the “Tools” key from the remote opens the tools bar on the top of the screen, but nothing related to launch any apps, or whatever…
Indeed I tried USB side loading as well without luck, as I can only browse the Plex folder content but no way to launch the app itself really...
Any help would be greatly appreciated! :)

![IMG_0063](https://user-images.githubusercontent.com/22093843/145458292-ab36069f-d660-4370-9d45-e8bb982ad14b.jpeg)
![IMG_0064](https://user-images.githubusercontent.com/22093843/145458316-b16dff02-6aae-45cb-9c41-0d3bf56cf34b.jpeg)

**Comment by kadrim** [comment]
Sorry, this will only work on E/F and H Series.

I will send you another reply on the plex forum https://forums.plex.tv/t/plex-app-orca-2-012-showing-user-offline/762872/43

**Comment by mmz06** [comment]
Well, at least I tried... ;-)
Thank you !
