### ISSUE TITLE
[FR] proxy4plex docker container 

### ISSUE THREAD

**Issue by goblinmaks** [kadrim/proxy4plex#3]
This is feature request. 
Could you please create docker image file for works in container.

**Comment by kadrim** [comment]
Maybe i don't see the real use case, please explain why one would need a Docker image?

I can of course build one, but the go-implementation supports literally all architectures and OSes with zero dependencies.

**Comment by goblinmaks** [comment]
For example, docker container is very simple way to update service. Not need make any changes to start services automatically

**Comment by kadrim** [comment]
Done.

**Comment by goblinmaks** [comment]
@kadrim It is possible to push image to dockerhub or to ghcr(https://github.com/features/packages) ?

**Comment by kadrim** [comment]
please check the commit and have a look at the updated readme.md. The image was already pushed to dockerhub at release.

https://hub.docker.com/r/kadrim/proxy4plex
