### ISSUE TITLE
Listening to ipv6 only

### ISSUE THREAD

**Issue by edgd1er** [kadrim/proxy4plex#4]
Hello,

I'm not sure this is a bug or a feature, but proxy4plex when executed on a amd64. is listening on a ipv6 address only.
the 2.014 plex app accept only ipv4 addresses.
Is there a way to disable listening to ipv6 addresses through an argument for instance ? (-4 like netstat)

```bash
sudo netstat -lnop | grep :3000
tcp6       0      0 :::3000                 :::*                    LISTEN      1790311/./proxy4ple  off (0.00/0/0)
sudo netstat -lnop | grep :80
tcp6       0      0 :::80                   :::*                    LISTEN      1790311/./proxy4ple  off (0.00/0/0)
```
when limiting to ipv4 @, no listening process are found.
```bash
sudo netstat -4lnop | grep :80
sudo netstat -4lnop | grep :3000
``` 
is this something other may have seen ?

**Comment by kadrim** [comment]
this is not a bug. 

by listening on `:::3000` and `:::80` the proxy is reachable on both ipv6 and ipv4 - on all available interfaces

Just try it with telnet:

`telnet 127.0.0.1 3000` (telnet to ipv4-localhost)

and

`telnet <your-ipv4> 3000`

**Comment by kadrim** [comment]
this is true for not just my proxy, but for apache, nginx and all the services that support ipv6.

Have a good read: https://unix.stackexchange.com/questions/152612/netstat-why-are-ipv4-daemons-listening-to-ports-listed-only-in-a-inet6

**Comment by edgd1er** [comment]
Thanks for the info, didn t know that. Sideloading is not working, I ll to continue searching why. (tv Ue40f6500sb) i got an error net development 02

**Comment by kadrim** [comment]
ok, if you need help, use the forums or, if you encounter a bug, open a new issue. 

when sideloading is not working and the log of the proxy does not record anything, i have 2 guesses:

1. is the TV on the same network as the proxy?
2. has the host running the proxy already something running on port 80? or some iptables magic? like a firewall?

**Comment by kadrim** [comment]
i would try running the second telnet command from yet another machine on your network, just to see, if the proxy is reachable.

**Comment by edgd1er** [comment]
I ran the command and I got results on port 80 and 3000 using ipv4 address, all seem ok on this side.

curl -vL http://192.168.53.208:3000/
```
* Expire in 0 ms for 6 (transfer 0x55bf2626eee0)
*   Trying 192.168.53.208...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x55bf2626eee0)
* Connected to 192.168.53.208 (192.168.53.208) port 3000 (#0)
> GET / HTTP/1.1
> Host: 192.168.53.208:3000
> User-Agent: curl/7.64.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Cache-Control: no-cache
< Content-Type: text/html; charset=utf-8
< Date: Thu, 16 Dec 2021 21:00:01 GMT
< Location: http://192.168.53.208:3000?url=https://plex.tv:3000/
< Referrer-Policy: origin-when-cross-origin
< Set-Cookie: _my-plex_session_32=MWJLVnBZVVhYaEJKanZSNm1aYjhibERldzE3RllrNldnQ1JhRXBXU3ZqQnpYSVlLWWtGaW5yQmZmb0JjQ0RKcVZqVFo4RVl6empTZUR5SGtnQ29kaHlndWovNmZFV2hUVkdaWk5vZEV2eTRoTmRjZjBjcmY5OGlyTzNxVmJ6VERSd1lxTmFtd29sNExGRVdhc1J5TEpJT1pydTQ3QzdYbDhSQUNJaXliVTBBPS0tNGRVQlFiY2ZuUDZJSWV3OGNFZzRsZz09--9d65571909c2f3969f3343d8d88dca0947a17035; path=/; HttpOnly; secure
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< Vary: Origin
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-Request-Id: f07200fb-b350-4c26-bfaf-d7b8a90f53ce
< X-Runtime: 0.002834
< X-Xss-Protection: 1; mode=block
< Content-Length: 87
< 
* Ignoring the response-body
* Connection #0 to host 192.168.53.208 left intact
* Issue another request to this URL: 'http://192.168.53.208:3000/?url=https://plex.tv:3000/'
* Found bundle for host 192.168.53.208: 0x55bf2626df10 [can pipeline]
* Could pipeline, but not asked to!
* Re-using existing connection! (#0) with host 192.168.53.208
* Connected to 192.168.53.208 (192.168.53.208) port 3000 (#0)
* Expire in 0 ms for 6 (transfer 0x55bf2626eee0)
> GET /?url=https://plex.tv:3000/ HTTP/1.1
> Host: 192.168.53.208:3000
> User-Agent: curl/7.64.0
> Accept: */*
>
```

curl -vL http://192.168.53.208/widgetlist.xml
```
* Expire in 0 ms for 6 (transfer 0x559864650ee0)
*   Trying 192.168.53.208...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x559864650ee0)
* Connected to 192.168.53.208 (192.168.53.208) port 80 (#0)
> GET /widgetlist.xml HTTP/1.1
> Host: 192.168.53.208
> User-Agent: curl/7.64.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Thu, 16 Dec 2021 20:51:48 GMT
< Content-Length: 318
< Content-Type: text/xml; charset=utf-8
< 
<?xml version="1.0" encoding="UTF-8"?>
		<rsp stat="ok">
				<list>
						<widget id="Plex_2.014_net">
								<title>Plex</title>
								<compression size="6451263" type="zip"/>
								<description/>
								<download>http://192.168.53.208/Plex_2.014_11112020_net.zip</download>
						</widget>
				</list>
```

**Comment by kadrim** [comment]
then the problem is somewhere else and not on the proxy-side. you can also sideload with samywidgets and then try to use the proxy. Maybe then you will find out why the sideloading does not work.

sideloading has only to be done once.
