### ISSUE TITLE
Feature: load local app or remote according to args.

### ISSUE THREAD

**Issue by edgd1er** [kadrim/proxy4plex#5]
Hello,

I had to wait 1.5hr to synchronize the app, as the proxy4plex didn't download the zip.All that time, I wandered what did I do wrong for the app not being uploaded to the tv. 

Is there a way to store the zip in the same directory as the app in order to avoid this delay ? may be with args, like -l to load local zip, -r to force download from remote ? At some points, the dropbox files may not be available and the sideloading will fail.

What do you think of it ?

```log
2021/12/17 21:25:15 Server starting on Port 3000 ...
2021/12/17 21:25:15 Trying to start app-deployer on port 80 ...

2021/12/17 23:00:42 checksum match. going on ...
Processing file: Plex/changelog.txt
Replacement: changelog.txt
Processing file: Plex/config.xml
Replacement: config.xml
Processing file: Plex/css/
Replacement: css/
Processing file: Plex/css/style.min.css
Replacement: css/style.min.css
Processing file: Plex/fonts/
.....
```

**Comment by kadrim** [comment]
good suggestion! will have a look into it!

**Comment by kadrim** [comment]
maybe also some sort of download bar, so the user does see, that something is happening

**Comment by kadrim** [comment]
Implement like this: if a local file with the correct SHA-sum is present, use it, otherwise download and save it. Also add some indication to the console log, that a download is happening.
