### ISSUE TITLE
Can't get menu on J model while Developper mode activated

### ISSUE THREAD

**Issue by zx97** [kadrim/proxy4plex#6]
Hello,

I am trying to fix the issue of Plex connection on my Samsung UJU7000 (2015) TV

Following the readme:

1. Start the proxy4plex binary
2. Open smarthub on your TV
3. Hit the Red button on the remote to login to an account
4. Use develop for username, password should fill automatically, if it does not, use 111111
5. Hit the Tools button on the remote and select Settings while within smarthub
6. Select the menu-entry Development and accept the agreement after reading it

I ran into step 1 on a NAS same subnet, executed as root and got this message:

root@localhost:/volume1/.@root # chmod 755 proxy4plex-0.3.1-0-g20c63b3-linux-amd64
root@localhost:/volume1/.@root # ./proxy4plex-0.3.1-0-g20c63b3-linux-amd64
2021/12/18 17:08:28 Server starting on Port 3000 ...
2021/12/18 17:08:28 Trying to start app-deployer on port 80 ...

then it waits and I can't see using netstat -n anything listening or with a connection established 

# netstat -n | grep  ':80'
tcp        0      0 10.0.0.200:8001         10.0.1.145:17461        ESTABLISHED
tcp        0      0 10.0.0.200:8001         10.0.1.145:17540        ESTABLISHED
tcp        0      0 10.0.0.200:50802        45.56.77.71:8003        ESTABLISHED

(10.0.0.200 and 10.0.1.145 are in same subnet btw 145 is my workstation)

I tried to execute on my Workstation as administrator the windows version also and get the same message,

So I assume it works as expected, then when I follow steps 3 it doesn't bring me to log in pge but anyway I did that using another menu entry (from the menu button then smarthub/connect). I also rebooted the TV and always have developer mode activated. I have added the IP of my PC using the 12345 trick in smarthub also.

When I try step 5 while in smarthub, I can see in red the "developer mode" string but the tool menu doesn't have any development entry.

I tried to install Tizen Studio also, can connect to TV but no idea how to send Plex 2.014 on TV as this doesn't seems to contain project file.

I am stuck looking for help and always looping in same method description which don't work for me.

Could you please help me to identify what I am doing wrong ?

B.R.

**Comment by ukdtom** [comment]
Try on an existing app to press and hold down the enter (Broken arrow) key on the remote
Does a menu then show?

**Comment by zx97** [comment]
![IMG20211218174458](https://user-images.githubusercontent.com/1134035/146649012-7abc2a88-d0c3-4ec9-81a7-4867abc532e7.jpg)

Yes, I can read (disabled as this is default app)  delete, the reinstall, move and print informations

**Comment by ukdtom** [comment]
Sadly doesn't have a J model, but did find this: https://www.partitionwizard.com/partitionmanager/how-to-install-3rd-party-apps-on-samsung-smart-tv.html

**Comment by zx97** [comment]
Thanks, I saw this page already this is for Android TV, but mine is quite older (bought in 2016 so model of 2015) with Tizen.

I was able to have an application using Tizen Studio but it's not working yet, I'll try to find if it's possible to send the plex zip file as-is, that would allow me to fix this definitely using you proxy.

I'll never buy a Samsung product ever, I had a smartphone and a TV and both of them become obsolete after a few years ...

**Comment by kadrim** [comment]
sadly, i don't have i J-Series to test different possibilities. Only the older H-Series (2014) and the very old E-Series (2012). The instructions i wrote are only wokring for E/F and H-Series.

I still don't know how the sideloading on the J-Series works. Maybe you and @mmz06 can work something out together?

Follow this forum-thread: https://forums.plex.tv/t/plex-app-orca-2-012-showing-user-offline/762872/49 i will try to help there aswell.

**Comment by zx97** [comment]
Thanks, I've posted to the thread and will follow.

**Comment by kadrim** [comment]
i will close this issue here, as it is currently working without proxy, because plex switched back to TLS 1.2 which J-Series can handle.

It sill needs to be determined how anyone can sideload the orca-app to a J-Series using `tizen studio` but that is out of scope for this proxy.
