### ISSUE TITLE
Display IP-Adresses in Console-Log

### ISSUE THREAD

**Issue by kadrim** [kadrim/proxy4plex#7]
as suggested by @ukdtom

> In your proxy console window, the initial msg is that it listen on port 3000
> Would make support life a tad more easy, if it also listed the IP 

It is however somewhat hard to get the wanted interface as most devices have multiple IPs (yes i could filter out the loopback devices) but when someone has virtualbox installed there are 2 more listed.

I would not be sure which one to display. Or would you just display all of them?

> Better than nothing IMHO

so the task is to display all IP-Adresses and then somehow determine the most likely one.

**Comment by ukdtom** [comment]
Maybe find the one that has a default gateway?
